# Project coordinates
group=de.zettsystems
version=1.0.0

# Plugins
foojayResolverVersion=1.0.0
benManesVersionsVersion=0.64.0
vanniktechPublishVersion=0.37.0

# Libraries
rewriteRecipeBomVersion=3.37.0
lombokVersion=1.18.48
logbackVersion=1.6.3
junitJupiterVersion=6.1.3
junitPlatformVersion=6.1.3
guavaVersion=33.7.1-jre
