# Project coordinates
group=de.zettsystems
version=1.0.1-SNAPSHOT

# Plugins
foojayResolverVersion=1.0.0
benManesVersionsVersion=0.64.0
vanniktechPublishVersion=0.37.0
errorproneGradleVersion=5.1.1
nullawayGradleVersion=3.2.0
spotbugsGradleVersion=6.5.11
sonarVersion=7.5.0.8588
jacocoVersion=0.8.15

# Libraries
rewriteRecipeBomVersion=3.37.0
lombokVersion=1.18.48
jspecifyVersion=1.0.1
errorproneCoreVersion=2.50.0
nullawayCoreVersion=0.14.1
logbackVersion=1.6.3
junitJupiterVersion=6.1.3
junitPlatformVersion=6.1.3
assertjVersion=3.27.7
guavaVersion=33.7.1-jre
