---
name: ci

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - master

env:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
  GRADLE_SWITCHES: "-s --console=plain --stacktrace"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: validate-gradle-wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: set-up-jdk
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: 25
          cache: gradle
      - name: build
        run: ./gradlew ${GRADLE_SWITCHES} build
